[versions]
android-gradle-plugin = "8.6.1"
androidx-appcompat = "1.7.0"
androidx-cardview = "1.0.0"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-fragment-ktx = "1.8.4"
androidx-multidex = "2.0.1"
androidx-navigation = "2.8.2"
androidx-recyclerview = "1.3.2"
firebase = "33.4.0"
gms = "4.4.2"
gradle-versions-plugin = "0.51.0"
iadvize-sdk = "2.14.3"
insetter = "0.6.1"
kotlin = "2.0.0"
kotlin-coroutines = "1.9.0"
material = "1.12.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "androidx-cardview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "androidx-multidex" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
iadvize-sdk = { group = "com.iadvize", name = "iadvize-sdk", version.ref = "iadvize-sdk" }
insetter = { group = "dev.chrisbanes.insetter", name = "insetter", version.ref = "insetter" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
androidx-navigation-safeargs-kotlin = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

[bundles]
androidx-navigation = ["androidx-navigation-fragment-ktx", "androidx-navigation-ui-ktx"]
firebase-tools = ["firebase-analytics", "firebase-messaging"]
